//! Hot-feature frontloading for the v9 threat-weight matrix.
//!
//! At NNUE load time, the 49 MB threat weight matrix
//! (`66864 features × 768 i8 weights`) is permuted so the
//! highest-activation features land at the lowest physical row
//! offsets. The permutation is baked from a 12,000-position activation
//! count measured by `threat_accum::tests::measure_feature_sparsity`
//! — top 706 features capture 50% of activations (540 KB, fits L2),
//! top 7,665 capture 90% (5.7 MB, fits L3 on small-cache hosts).
//!
//! The on-disk net file format is unchanged — permutation is in-memory
//! only. `threat_index()` is wrapped to return the permuted index, so
//! every weight-row access naturally hits the frontloaded position.
//! Inference output is bit-identical to pre-frontload.
//!
//! Targets the `apply_threat_deltas` L1-miss hotspot directly:
//! `apply_threat_deltas` is 21.5% of search-bench cycles and the bulk
//! of its time is reading 49 MB-spread weight rows. Frontloading puts
//! the hot half of activations into a 540 KB hot region that stays
//! L2-resident across pushes.

#![allow(dead_code)]

/// Number of threat features baked into the permutation. Must match
/// the production v9 threat-feature count (see threats.rs init).
pub const THREAT_PERM_FEATURE_COUNT: usize = 66864;

/// Embedded permutation blob: `[u32_le; THREAT_PERM_FEATURE_COUNT]`.
///
/// `THREAT_PERM[orig_idx] = permuted_idx` — where the feature with
/// original index `orig_idx` ends up after frontloading. Rank 0 is the
/// hottest feature.
///
/// Generated by running:
/// ```ignore
/// CODA_DUMP_FEATURE_PERM=data/threat_feature_perm.bin \
///   cargo test --release measure_feature_sparsity -- --nocapture --ignored
/// ```
/// The measurement uses 30 games × 5 starts × 80 plies = 12,000
/// positions with a deterministic LCG seed, so the resulting
/// permutation is reproducible across hosts.
const THREAT_PERM_BYTES: &[u8] = include_bytes!("../data/threat_feature_perm.bin");

/// Decode the embedded permutation into a `Vec<u32>` of length
/// `THREAT_PERM_FEATURE_COUNT`. Safe to call multiple times; cache via
/// `OnceLock` if hot.
pub fn load_permutation() -> Vec<u32> {
    assert_eq!(
        THREAT_PERM_BYTES.len(),
        THREAT_PERM_FEATURE_COUNT * 4,
        "embedded threat-perm blob is the wrong size — regenerate via measure_feature_sparsity"
    );
    let mut perm = Vec::with_capacity(THREAT_PERM_FEATURE_COUNT);
    for chunk in THREAT_PERM_BYTES.chunks_exact(4) {
        let bytes = [chunk[0], chunk[1], chunk[2], chunk[3]];
        perm.push(u32::from_le_bytes(bytes));
    }
    perm
}

/// In-place permute a threat weight matrix from "trained order" to
/// "frontloaded order". `threat_weights` is a flat `[i8; nf * h]` where
/// row `i` is `threat_weights[i*h..(i+1)*h]`. The permutation maps
/// trained-order row `orig_idx` to frontloaded-order position
/// `perm[orig_idx]`.
///
/// Memory: allocates one scratch buffer of size `threat_weights.len()`
/// (≈49 MB for v9 prod). Could be in-place via cycle-following but the
/// extra copy keeps the code straightforward and runs once per net load.
pub fn permute_threat_weights(threat_weights: &mut [i8], num_features: usize, hidden_size: usize) {
    if num_features != THREAT_PERM_FEATURE_COUNT {
        // Permutation only valid for the production v9 feature count.
        // Other configurations (test nets, different threat-feature schemes)
        // skip frontloading.
        return;
    }
    debug_assert_eq!(threat_weights.len(), num_features * hidden_size);
    // Initialize the hot-path pointer table on first net load; safe because
    // NNUE load is single-threaded.
    unsafe { ensure_perm_table_initialized(); }
    let perm = load_permutation();
    let mut scratch = vec![0i8; threat_weights.len()];
    for orig_idx in 0..num_features {
        let new_idx = perm[orig_idx] as usize;
        let src_off = orig_idx * hidden_size;
        let dst_off = new_idx * hidden_size;
        scratch[dst_off..dst_off + hidden_size]
            .copy_from_slice(&threat_weights[src_off..src_off + hidden_size]);
    }
    threat_weights.copy_from_slice(&scratch);
}

/// Pre-decoded permutation table, populated at NNUE load time when
/// `permute_threat_weights` runs. Read-only thereafter on the hot path.
///
/// Using a non-atomic static + load-time init is faster than `OnceLock`
/// because the hot path is a plain pointer-load instead of an atomic
/// + branch. Initialization is single-threaded (NNUE load on the main
/// thread before any search starts), so this is sound.
static mut PERM_TABLE_PTR: *const u32 = std::ptr::null();
static mut PERM_TABLE_LEN: usize = 0;
static mut PERM_TABLE_STORAGE: Option<Box<[u32]>> = None;

unsafe fn ensure_perm_table_initialized() {
    if PERM_TABLE_PTR.is_null() {
        let v = load_permutation().into_boxed_slice();
        PERM_TABLE_PTR = v.as_ptr();
        PERM_TABLE_LEN = v.len();
        PERM_TABLE_STORAGE = Some(v);
    }
}

/// Apply the permutation to a single feature index. Returns the
/// frontloaded position for the given trained-order index.
///
/// Caller must call this AFTER `permute_threat_weights` has run on the
/// net's weight matrix (which happens once at load time). Otherwise the
/// indices and the matrix are out of sync.
///
/// Hot path: one load + bounds compare. The pointer is filled at
/// NNUE load time; reads are wait-free.
#[inline(always)]
pub fn perm_feature_index(orig_idx: usize) -> usize {
    unsafe {
        if PERM_TABLE_PTR.is_null() || orig_idx >= PERM_TABLE_LEN {
            return orig_idx;
        }
        *PERM_TABLE_PTR.add(orig_idx) as usize
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn perm_blob_decodes() {
        let perm = load_permutation();
        assert_eq!(perm.len(), THREAT_PERM_FEATURE_COUNT);
        // Sanity: every position 0..nf appears exactly once
        let mut seen = vec![false; THREAT_PERM_FEATURE_COUNT];
        for &p in &perm {
            let idx = p as usize;
            assert!(idx < THREAT_PERM_FEATURE_COUNT, "perm value out of range: {}", idx);
            assert!(!seen[idx], "duplicate perm value: {}", idx);
            seen[idx] = true;
        }
        for (i, &was_seen) in seen.iter().enumerate() {
            assert!(was_seen, "missing perm value at position {}", i);
        }
    }

    #[test]
    fn perm_feature_index_matches_load_permutation() {
        let perm = load_permutation();
        for &idx in &[0, 1, 100, 1000, 10000, 50000, 66863] {
            assert_eq!(perm_feature_index(idx), perm[idx] as usize);
        }
    }
}
